import { ContentType, PreviewSize } from '../enums/light-box.enums';
import { VideoSize } from '../enums/video.enums';
import { ProjectContentModel } from '../models/project-config.model';

export const ProjectOtpCustomToolContent: ProjectContentModel = {
  title: 'Order Tracking Portal – Real-Time Dev Tool',
  content: [
    {
      type: ContentType.IMAGES,
      previewSize: PreviewSize.MEDIUM,
      images: [
        {
          imageSrc: 'images/project-otp/wapple.jpg',
          imageAlt: 'Custom Tool Preview',
          imageLabel: 'Dashboard UI of the real-time dev tool',
        },
      ],
      label: '',
    },
    {
      type: ContentType.TEXT,
      label: '',
      content: `This internal tool was built to simplify development and debugging of real-time features in the Woolworths Order Tracking Portal. It mimicked the production SignalR event stream generated by the Live Delivery Tracking service, which was difficult to run locally due to its dependency on service bus events.`,
    },
    {
      type: ContentType.HEADING,
      content: 'What it did:',
    },
    {
      type: ContentType.LIST,
      items: [
        'Mocked the real-time SignalR hub used by the production backend, matching the exact message format.',
        'Enabled developers to simulate the full delivery tracking journey — forward, backward, or skipping stages.',
        'Allowed sending of custom payloads to test edge cases and preview upcoming features.',
        'Provided a live preview window with iframe support for viewing the Order Tracking Portal at various screen sizes.',
        'Converted from a personal console app into a shared Angular front-end for team-wide use.',
      ],
      label: '',
    },
    {
      type: ContentType.HEADING,
      content: 'Tech stack:',
    },
    {
      type: ContentType.LIST,
      items: [
        'Backend: C# (.NET Core) SignalR service',
        'Frontend: Angular SPA to manage events, payloads, and preview settings',
        'WebSocket bridge: Mimicked LDT service behaviour in real time',
        'Iframe sandbox for running the Order Tracking Portal locally with dev settings',
      ],
      label: '',
    },
    {
      type: ContentType.TEXT,
      label: '',
      content: `The tool was initially a solo project, triggered via keystrokes in a console app. Once other developers expressed interest, I built a frontend and shared the code via a Woolworths repo to encourage collaboration. The project helped significantly reduce local dev friction and improved our ability to test dynamic user journeys.

While I’d love to showcase some of the backend implementation, the tool is still in use internally and the code may contain sensitive logic or references. As a result, I can’t publicly share the repository or source files.`,
    },
    {
      type: ContentType.VIDEO,
      src: 'images/project-otp/tool-demo-1080p.mp4',
      label: 'Walkthrough of the custom tool in action',
      videoSize: VideoSize.MEDIUM,
    },
  ],
};
